name: CI

# Esse passo é executado somente após o push do meu repositório
on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
  
jobs:  
  build:    
    runs-on: ubuntu-latest    
    
    steps:      
      - uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build
        
#      Atualizando as dependências para a instância EC2 utilizando uma action Github SCP     
      - uses: appleboy/scp-action@master
        with:          
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}          
          key: ${{ secrets.SSH_KEY }}          
          port: ${{ secrets.SSH_PORT }}          
          source: "., !node_modules, !ormconfig.json, !docker-compose.yaml" 
          target: "~/app/Rentx"
         
      #Atualizando a aplicação (ex: atualizando as dependências na pasta node_modules, rodando migrations e restartando a aplicação)   
      - name: Update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}          
          key: ${{ secrets.SSH_KEY }}          
          port: ${{ secrets.SSH_PORT }}          
          script: | 
            cd ~/app/Rentx 
            yarn
            ./node_modules/.bin/typeorm migration:run
            pm2 restart rentx_api
      
