name: CI

# Esse passo é executado somente após o push do meu repositório
on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
  
jobs:  
  build:    
    runs-on: ubuntu-latest    
    
    steps:      
      - uses: actions/checkout@v3
      
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build
        
#      Atualizando as dependências para a instância EC2 utilizando uma action Github SCP     
      - uses: appleboy/scp-action@master
        with:          
          username: ${{ secrets.SSH_USER }}                    
          key: ${{ secrets.SSH_KEY }}          
          source: "., !node_modules" 
          target: "test"
      
